# Generated by Django 4.2.3 on 2023-07-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
