# Generated by Django 4.2.3 on 2023-07-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0008_alter_plot_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='owner',
            new_name='user',
        ),
    ]
